### ISSUE TITLE
Add Pause/Resume Functionality

### ISSUE THREAD

**Issue by nicolaslevy** [englishm/moq-js#5]
Currently, the player starts playback automatically (autoplay) upon initialization. This feature request aims to add the ability to pause and resume playback. The expected behavior is:

* When the player is paused, it should unsubscribe from all tracks.
* When resumed, the player should resubscribe to the previously active tracks.

The UI, including the toggle button for play/pause, will be implemented as part of Issue [<#7>](https://github.com/englishm/moq-js/issues/7).

**Comment by JoaquinBCh** [comment]
I'll take this ticket.

**Comment by nicolaslevy** [comment]
FYI, work is being done in  https://github.com/englishm/moq-js/pull/9

**Comment by englishm** [comment]
Done by @JoaquinBCh in https://github.com/englishm/moq-js/pull/9. Thanks!
