### ISSUE TITLE
Add Mute/Unmute Functionality to the Player

### ISSUE THREAD

**Issue by nicolaslevy** [englishm/moq-js#6]
Implement the mute/unmute functionality in the player. The expected behavior is as follows:

* When the player is muted, it should unsubscribe from the audio track.
* When unmuted, the player should resubscribe to the same audio track.

The UI, including the toggle button for mute/unmute, will be implemented as part of Issue [<#7>](https://github.com/englishm/moq-js/issues/7).

**Comment by mcintyrehh** [comment]
Going to pick this one up!

**Comment by nicolaslevy** [comment]
Let's close this issue as the feature is already merged!! :partying_face:
