### ISSUE TITLE
Add Basic Player (UI) Controls

### ISSUE THREAD

**Issue by nicolaslevy** [englishm/moq-js#7]
This issue focuses on implementing basic graphical controls for the player. These controls will allow users to interact with existing functionalities visually, such as:

* [Play/Pause](https://github.com/englishm/moq-js/issues/5)
* [Mute/Unmute](https://github.com/englishm/moq-js/issues/6)
* [Track selection](https://github.com/englishm/moq-js/pull/3)

The goal is to enhance usability by providing a fully functional graphical interface for these operations like any well know DASH/HLS player.

**Comment by christriants** [comment]
I will pick this one up!

**Comment by nicolaslevy** [comment]
Maybe we could look some of the work done for [player.style](https://player.style/),

The player.style project is a initiative to crate themes for any player, we can bring some ideas or use it as reference to know  how other players create their interfaces.
